src/main/java/uk/co/real_logic/agrona/concurrent/UnsafeBuffer.java

32 bit rather than 64 put of a long (if this code is ever used).

UnsafeBuffer.java - correct type conversion size issue.

---

src/main/java/uk/co/real_logic/agrona/concurrent/broadcast/BroadcastBufferDescriptor.java
src/main/java/uk/co/real_logic/agrona/concurrent/ringbuffer/RingBufferDescriptor.java

Take with a pinch of salt as am still getting familiar with the project. But it looks like current Trailer has 128 byte length but the three fields are packed into the first 24 bytes. i.e. they'll all be sharing a cache line + the second cache line will be completely empty.
I've just stolen the code from the RingBuffer descriptor as a tentative fix.
Again... pinch of salt but see what you think.
Cheers,
A.

Might be problem with offsets in BroadcastBufferDescriptor.

---

src/main/java/uk/co/real_logic/agrona/collections/Int2IntHashMap.java
src/test/java/uk/co/real_logic/agrona/collections/Int2IntHashMapTest.java

Size field should be reset during rehash() to avoid counting current entries multiple times.

Fixed Int2IntHashMap/Long2LongHashMap.size(). 

---

src/main/java/uk/co/real_logic/agrona/concurrent/MappedResizeableBuffer.java
src/test/java/uk/co/real_logic/agrona/concurrent/MappedResizeableBufferTest.java

While reading the code, I noticed that the doc was cut in the middle of a sentence. 
Here is my proposal to complete it and also add more information about the behavior of the buffer  close().

[Java] Improve javadoc

---

src/main/java/uk/co/real_logic/agrona/concurrent/UnsafeBuffer.java

This is fix for a bug introduced in rollback of long index changes, address should be long.

converting address to long in UnsafeBuffer constructor

---

src/main/java/uk/co/real_logic/agrona/concurrent/AgentRunner.java
src/main/java/uk/co/real_logic/agrona/concurrent/BackoffIdleStrategy.java

This pull request is focused on resolving occurrence of Sonar rule
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1213
Please let me know if you have any questions.
George Kankava

squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

---

src/main/java/uk/co/real_logic/agrona/collections/IntIntConsumer.java
src/main/java/uk/co/real_logic/agrona/collections/IntObjConsumer.java
src/main/java/uk/co/real_logic/agrona/concurrent/CountersReader.java
src/test/java/uk/co/real_logic/agrona/concurrent/CountersManagerTest.java

`CountersReader.forEach()` takes a `java.util.function.BiConsumer` as parameter, and pass it the counterId (int) and label (String). Using a `BiConsumer` causes the counter to be boxed.
This pull requests creates a new functional interterace `IntObjConsumer` in agrona/collections and uses it in `CountersReader.forEach()` to avoid the boxing. This new interface is very similar to `ObjIntConsumer` from the JDK but with parameters order reversed to be backward compatible with current uses of forEach(), but I may remove it and use the JDK's one if it seems overkill to add an almost duplicate interface.
I also fixed a little error in the doc of `IntIntConsumer` that was saying `long` instead of `int`

Avoid boxing in CountersReader.forEach()

---

src/main/java/org/agrona/TimerWheel.java
src/test/java/org/agrona/TimerWheelTest.java

Motivation:
As described in Issue #71, expose method ```Iterable<Timer> TimerWheel#scheduled()``` to get iterable thru all timers scheduled on the TimerWheel, which makes it possible to implement in client code some immediate actions on scheduled tasks if it's required by shutdown semantic for example.

Issue #71: Expose TimerWheel#scheduled()

---

src/main/java/org/agrona/collections/IntHashSet.java
src/test/java/org/agrona/collections/IntHashSetTest.java

I've fixed the `IntHashSet.containsAll(Collection)` method. When writing tests I've also found that there are some problems with `IntHashSet.containsAll(IntHashSet)`, which I've also fixed. Plus, renamed `conjunction` to `disjunction` according to what it does.
Edit: it might be a good idea to write some tests for `addAll` and `removeAll`. I could push another commit to this pull request. Shall I?

Issue #75: [Java] Fixed IntHashSet.containsAll.

---

src/main/java/org/agrona/collections/ObjHashSet.java
src/main/java/org/agrona/collections/ObjIterator.java
src/test/java/org/agrona/collections/ObjHashSetTest.java
src/test/java/org/agrona/collections/ObjHashSetTestInteger.java
src/test/java/org/agrona/collections/ObjHashSetTestString.java

This is a new `Set` implementation for `Object`s.  It is based on the `IntHashSet` but takes `Object`s rather than primitives.
Like `IntHashSet` (unlike `HashSet` based on `HashMap`) it is suitable for environments where allocation is not an option.
One thing I have added is a ability to be notified when the collection is resized.  The idea is that a warning could be implemented during testing allowing appropriate capacity to be set in the constructor so that when deployed for real there should be no need for resizing.
I have added 2 test classes, again based on the tests written for `IntHashSet`.
Please review and if you think it will enhance the library please add.
Daniel

New Set implementation for Objects

---

build.gradle

This ensures that OSGi compatible meta data is generated and added to
the jar's manifest. So the artifact can be used as OSGi bundle in an
OSGi container.
This is analogous to the pull request I created for the Aeron project. As Aeron depends on Agrona, Agrona should support OSGi, too.

Added Gradle OSGi plugin.

---

agrona/src/main/java/org/agrona/AsciiEncodingHelper.java
agrona/src/main/java/org/agrona/DirectBuffer.java
agrona/src/main/java/org/agrona/ExpandableArrayBuffer.java
agrona/src/main/java/org/agrona/ExpandableDirectByteBuffer.java
agrona/src/main/java/org/agrona/MutableDirectBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/concurrent/UnsafeBufferTest.java

Pull Request for #117 to make changes easier to review.

Add natural, int and long parse and put methods for the buffer hierarchy

---

agrona/src/main/java/org/agrona/collections/IntHashSet.java
agrona/src/main/java/org/agrona/collections/ObjectHashSet.java
agrona/src/test/java/org/agrona/collections/IntHashSetTest.java
agrona/src/test/java/org/agrona/collections/ObjectHashSetIntegerTest.java

[Java] Make hashset (int and object) Set::equals compatible

---

agrona/src/main/java/org/agrona/collections/Int2ObjectCache.java

Multiplications on recent CPUs are not expensive as division/modulo ones, but using power of 2 would allow to turn them in faster shift without compromising any optimal configurations of the cache's set size.

[Java] Force power of 2 setSize on Int2ObjectCache to use shift instead of multiplication

---

agrona/src/main/java/org/agrona/collections/IntArrayList.java
agrona/src/test/java/org/agrona/collections/IntArrayListTest.java

This fixes a bug in `IntArrayList#addInt(index, element)` if the current capacity will be reached after the insert. The `System.arraycopy` used the new size instead of the current one to calculate the length of the copy. This will lead to an `ArrayIndexOutOfBoundsException` as it tries to copy the last element of the array to outside of the array bounds.

[Java] Use current size for array copy in IntArrayList

---

agrona-agent/src/main/java/org/agrona/agent/BufferAlignmentInterceptor.java

BufferAlignmentException message always tell zero as the Buffer Alignment Offset

BufferAlignmentException message misleading

---

agrona/src/main/java/org/agrona/collections/IntArrayList.java
agrona/src/test/java/org/agrona/collections/IntArrayListTest.java

Add fast unordered remove to primitive int collections (and longs through primitive expander).
Basically removes an element faster by overwriting with the last element (breaks order). This is instead of #134 because that approach is not allocation-free and the point of that change was to allow this in the primitive collections.

Add unordered remove to primitive collection

---

agrona/src/main/java/org/agrona/ReferenceHelper.java
agrona/src/test/java/org/agrona/ReferenceHelperTest.java

I'd like to use org.agrona as a stable home for ReferenceHelper. The JavaDoc explains its purpose to some degree, but let me elaborate here:
There is currently a deficiency in the Java Reference class API (which I would like to suggest fixes to over time via a JEP): Two common operation idioms that are used in most WeakReference-based data structured can currently only be performed by using a Reference.get(), which explicitly creates a strong reference to the referent and can prevent its collection on concurrent collectors. The two operations are isCleared() (usually done by evaluating (ref.get() == null) and isReferingTo (usually done by evaluating (ref.get() == obj)). Examples of these operations can be seen in e.g. [WeakIdentityHashMap](https://github.com/unofficial-openjdk/openjdk/blob …

Adds ReferenceHelper class

---

agrona/src/main/java/org/agrona/collections/Int2NullableObjectHashMap.java
agrona/src/main/java/org/agrona/collections/Int2ObjectHashMap.java
agrona/src/main/java/org/agrona/collections/NullReference.java
agrona/src/main/java/org/agrona/collections/Object2NullableObjectHashMap.java
agrona/src/main/java/org/agrona/collections/Object2ObjectHashMap.java
agrona/src/main/java/org/agrona/generation/PrimitiveExpander.java
agrona/src/test/java/org/agrona/collections/ConformanceTestsSuite.java
agrona/src/test/java/org/agrona/collections/Int2NullableObjectHashMapConformanceTest.java
agrona/src/test/java/org/agrona/collections/Int2ObjectHashMapTest.java
agrona/src/test/java/org/agrona/collections/Long2NullableObjectHashMapConformanceTest.java
agrona/src/test/java/org/agrona/collections/Object2NullableObjectHashMapConformanceTest.java

This is a variation of #153, that adds the nullability of values to `Object2ObjectHashMap`, `Int2ObjectHashMap` + `Long2ObjectHashMap`. It's basically identical to the other PR, except that the nullability of the map values is optional via `xyz2NullableObjectHashMap`. `BiInt2ObjectHashMap` although allows `null` values.
Note: this PR does _not_ include the fix for `Object2ObjectHashMap.AbstractIterator.remove()`, because it's not implicitly required for this variant of #153.

Allow null values

---

agrona/src/main/java/org/agrona/SystemUtil.java
agrona/src/test/java/org/agrona/SystemUtilTest.java
agrona/src/test/resources/TestFileA.properties
agrona/src/test/resources/TestFileB.properties

This PR changes the behaviour for SystemUtil.loadPropertiesFile so that system properties are correctly loaded. 
I've also added a couple of tests 
- one which documents the behaviour for loadProperties 
- another which documents how properties are merged between systemprops and props from a file.

[Java] Correctly load system properties in SystemUtil

---

agrona/src/main/java/org/agrona/ExpandableArrayBuffer.java
agrona/src/main/java/org/agrona/MutableDirectBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/concurrent/UnsafeBufferTest.java

I was a bit baffled for a few moments why IDEA didn't want to skip over a method in debug mode. It turns out the debugger calls toString() on objects quite profusely.
UnsafeBuffer#toString() if it is backed by an array will print the content of the array. For large arrays this doesn't quite work out.
I added a property so it is possible to disable the printout while maintaining backward compatibility. If it is not an issue, maybe better to just go without printing the content altogether?
Also added for ExpandableArrayBuffer.

Ability to disable array content printout on UnsafeBuffer#toString().

---

agrona/src/main/java/org/agrona/concurrent/ShutdownSignalBarrier.java

* Prevent concurrent add/remove to/from list of latches in `ShutdownSignalBarrier`
* Add a method to signal all registered latches

[Java] Make synchronisation around shutdown latches more robust

---

agrona/src/main/java/org/agrona/PrintBufferUtil.java
build.gradle

hi! My colleagues had some experiments with Netty and they showed me beautiful logging of byte buffers and I thought that it would be nice to have in aeron for debug purposes. 
So I adopted that code for `MutableDirectBuffer`
results seems like this  
for buffer 
```java
final UnsafeBuffer buffer = new UnsafeBuffer(new byte[128]);
final int length = buffer.putIntAscii(INDEX, -123);
System.out.println(PrintBufferUtil.prettyHexDump(buffer));
```
output will be  
```
+-------------------------------------------------+
|  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 2d 31 32 33 00 00 00 00 00 00 00 00 00 00 00 |.-123...........|
|00000010| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 …
```

[Java] add an util method for buffer's pretty hex dump

---

agrona/src/main/java/org/agrona/AsciiEncoding.java
agrona/src/main/java/org/agrona/AsciiNumberFormatException.java
agrona/src/test/java/org/agrona/AsciiEncodingTest.java

Allows users to specifically handle errors occurring when a non-ascii digit is attempted to be parsed. Extends NumberFormatException for backwards compatibility

AsciiEncoding::GetDigit to throw a AsciiNumberFormatException.

---

agrona/src/main/java/org/agrona/CloseHelper.java

A common situation is that you want to cleanup multiple of closeable objects. The existing close helper methods aren't very useful as they either suppress the exception or fail to guarantee that everything was closed. Here's a pair of utility methods from Artio that take a list or var-args array of closeables, guarantee they're all closed and don't suppress an exception if there is one. Pull requesting as I've had requests from other people for using this kind of method in non-artio projects and it agrona makes sense as a location.

Close all methods

---

build.gradle

This change moves to using the biz.aQute.bnd Gradle plugin to
produce OSGi-compatible manifests in jar files. Currently, only the
org.agrona.core module has been updated to provide OSGi metadata
because the Agrona agent should never need to be visible inside an
OSGi container. Care has been taken to preserve the existing defined
manifest fields (Automatic-Module-Name, Implementation-Title, etc).

Add OSGi support

---

agrona/src/main/java/org/agrona/AsciiEncoding.java
agrona/src/test/java/org/agrona/AsciiEncodingTest.java

Modify AsciiEncoding.parseIntAscii() and AsciiEncoding.parseLongAscii() to behave like java.lang.Integer.parseInt() and java.lang.Long.parseLong() respectively when it comes to handling lone signs.

AsciiEncoding.parseLongAscii() throw instead of returning zero for "-"

---

agrona/src/main/java/org/agrona/ExpandableRingBuffer.java
agrona/src/test/java/org/agrona/ExpandableRingBufferTest.java

The buffer increases capacity even when there is available space at the end of the buffer.

Fix bug in ExpandableRingBuffer

---

agrona-benchmarks/src/main/java/org/agrona/Crc32Benchmark.java
agrona/src/main/java/org/agrona/Checksums.java
agrona/src/test/java/org/agrona/ChecksumsTest.java

Currently `Checksums#crc32` always delegates to the `java.util.zip.CRC32`class from the JDK to compute actual checksum. This PR switches to the `java.util.zip.CRC32C` class added in JDK 9, because it offers a better performance.
Here are the benchmark results after the switch on different JDK versions:
```
-- JDK 8 [OpenJDK Runtime Environment (Zulu 8.42.0.23-CA-macosx) (build 1.8.0_232-b18)]
Benchmark                   (length)  Mode  Cnt    Score   Error  Units
Crc32Benchmark.crc32Native         8  avgt   25   10.469 ± 0.218  ns/op
Crc32Benchmark.crc32Native        32  avgt   25   14.744 ± 0.121  ns/op
Crc32Benchmark.crc32Native       128  avgt   25   19.667 ± 0.294  ns/op
Crc32Benchmark.crc32Native       256  avgt   25   23.427 ± 0.298  ns/op
Crc32Benchmark.crc32Native      1376  avgt …
```

Switch to CRC-32C when on JDK 9+

---

agrona/src/main/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBuffer.java
agrona/src/main/java/org/agrona/concurrent/ringbuffer/OneToOneRingBuffer.java
agrona/src/main/java/org/agrona/concurrent/ringbuffer/RingBuffer.java
agrona/src/main/java/org/agrona/concurrent/ringbuffer/RingBufferDescriptor.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBufferConcurrentTest.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBufferTest.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/OneToOneRingBufferConcurrentTest.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/OneToOneRingBufferTest.java

With the new `tryClaim` API it is possible to implement zero-copy publication by writing directly to the underlying ring-buffer.
Implementation details:
- `tryClaim` - reserves space in the underlying buffer and writes a header with the given `msgTypeId` and a negative record length
- `commit` - flips the sign on the record length field
- `abort` - writes `PADDING_MSG_TYPE_ID` into the type field and flips the sign on the record length field
Example of API usage:
```
final RingBuffer ringBuffer = ...;
final int index = ringBuffer.tryClaim(msgTypeId, messageLength);
if (index >= 0)
{
try
{
final AtomicBuffer buffer = ringBuffer.buffer();
// Work with the buffer directly using the index
...
ringBuffer.commit(index); // commit message
}
catch (final Throwable t)
{
ringBuffer.abort(index); // …
```

[Java] Add `tryClaim` API to the RingBuffer

---

build.gradle

Switch to `maven-publish` plugin while keeping most of existing logic. The biggest change is the switch to upload only shadow artifacts for `agrona-agent`, i.e. `agrona-agent-all` was removed and existing artifacts now represent shadow jar and the corresponding sources and javadoc.

[Java] Use `maven-publish` instead of deprecated `maven` plugin

---

agrona/src/main/java/org/agrona/collections/Int2IntHashMap.java
agrona/src/main/java/org/agrona/collections/Int2ObjectHashMap.java
agrona/src/main/java/org/agrona/collections/Object2IntHashMap.java
agrona/src/main/java/org/agrona/collections/Object2ObjectHashMap.java
agrona/src/test/java/org/agrona/collections/Int2IntHashMapTest.java
agrona/src/test/java/org/agrona/collections/Int2ObjectHashMapTest.java
agrona/src/test/java/org/agrona/collections/Object2IntHashMapTest.java
agrona/src/test/java/org/agrona/collections/Object2ObjectHashMapTest.java

Fixes 4 out of the 5 Map implementations in org.agrona.collections. The remaining, `Int2ObjectCache` is missing the required `allocateDuplicateEntry()` method in the iterator.

fix toArray() for Maps avoiding allocation

---

agrona/src/main/java/org/agrona/BufferUtil.java
agrona/src/main/java/org/agrona/IoUtil.java
agrona/src/test/java/org/agrona/BufferUtilTest.java

This PR includes:
- Methods to free ByteBuffers
- Delegate `IoUtil#unmap(MappedByteBuffer)` to `BufferUtil#free(ByteBuffer)`
- Use `MethodHandles` instead of reflection in `IoUtil`

[Java] Add BufferUtil#free methods to free direct ByteBuffers

---

agrona/src/main/java/org/agrona/concurrent/HighResolutionClock.java
agrona/src/main/java/org/agrona/concurrent/OffsetEpochNanoClock.java
agrona/src/main/java/org/agrona/concurrent/SystemEpochNanoClock.java
agrona/src/test/java/org/agrona/concurrent/OffsetEpochNanoClockTest.java

On my desktop - 2019 Ryzen - this was repeatedly able to get below the threshold in 3-4 samples running cold on startup.

add in a zero-gc alternative implementation of the EpochNanoClock

---

agrona/src/test/java/org/agrona/concurrent/OffsetEpochNanoClockTest.java

Have experimented with reproducing test failures here by running until test fails. This approach sadly introduces a timed park to the test but it managed 50k test runs without failure. I could not see another approach to achieve better reliability in this case.

improve test reliability

---

agrona/src/main/java/org/agrona/AsciiEncoding.java
agrona/src/test/java/org/agrona/AsciiEncodingTest.java

Empty string results in NumberFormatException. Attempt to read outside string boundaries (or negative length) in IndexOutOfBoundsException.
This behaviour is consistent with Integer::parseInt / Long::parseLong, and makes a slightly more usable API which does not force callers to catch 2 exceptions for the same kind of error - non-numeric input value. Incorrect usage still results in IndexOutOfBoundsException.
As I understand this is performance-sensitive call, I've run some benchmarks to parse 1 million numbers and try to evaluate effect of the special-case for `length <=1`
- mix of random 1- and 2- digit numbers (80/20)
- random numbers which are multiple of 1 million in 1-50m range
- random non-negative numbers
- mix of random negative and non-negative numbers
On my machine first case …

[Java] Make AsciiEncoding throw exceptions similar to JDK parseInt/parseLong

---

agrona/src/main/java/org/agrona/collections/Int2IntCounterMap.java
agrona/src/main/java/org/agrona/collections/Int2IntHashMap.java
agrona/src/main/java/org/agrona/collections/Object2ObjectHashMap.java

I believe capacity should be equal to a half of the array length, not a quarter.

[Java] Fix map capacity calculation

---

agrona/src/main/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBuffer.java
agrona/src/main/java/org/agrona/concurrent/ringbuffer/OneToOneRingBuffer.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBufferTest.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/OneToOneRingBufferTest.java

The `RingBuffer` is always created empty disregarding the content of the underlying `AtomicBuffer`. This is necessary to ensure correctness of the read/write operations.

[Java] Create RingBuffers as empty, i.e. pre-zero first record header and reset metadata section.

---

agrona/src/main/java/org/agrona/concurrent/SnowflakeIdGenerator.java
agrona/src/test/java/org/agrona/concurrent/SnowflakeIdGeneratorTest.java

Both `nodeIdBits` and `sequenceBits` can be set to zero but a combination of these values must not exceeds twenty two bits.
I've also moved rhs padding to a separate class:
- Before:
```
***** Hotspot Layout Simulation (JDK 8, 64-bit model, compressed references, compressed class pointers, 8-byte aligned)
org.agrona.concurrent.SnowflakeIdGenerator object internals:
OFF  SZ                               TYPE DESCRIPTION                                           VALUE
0   8                                    (object header: mark)                                 N/A
8   4                                    (object header: class)                                N/A
12   1                               byte AbstractSnowflakeIdGeneratorPadding.p000              N/A
13   1 …
```

[Java] Make nodeIdBits and sequenceBits configurable.

---

agrona-benchmarks/src/main/java/org/agrona/concurrent/UnsafeBufferPutIntAsciiBenchmark.java
agrona-benchmarks/src/main/java/org/agrona/concurrent/UnsafeBufferPutLongAsciiBenchmark.java
agrona/src/main/java/org/agrona/AsciiEncoding.java
agrona/src/main/java/org/agrona/ExpandableArrayBuffer.java
agrona/src/main/java/org/agrona/ExpandableDirectByteBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/ExpandableArrayBufferTest.java
agrona/src/test/java/org/agrona/ExpandableDirectByteBufferTest.java
agrona/src/test/java/org/agrona/concurrent/UnsafeBufferTest.java

This PR uses lookup table approach to optimize `putIntAscii`, `putNaturalIntAscii`, `putLongAscii` and `putNaturalLongAscii` methods by dividing by `100` and looking up two digits at a time. I'm see up to **23%** performance improvement.
This work was inspired by https://github.com/miloyip/itoa-benchmark and https://www.slideshare.net/andreialexandrescu1/three-optimization-tips-for-c?next_slideshow=1.
Here is the results I got:
- Before:
```
Benchmark                                       (value)  Mode  Cnt   Score   Error  Units
UnsafeBufferPutIntAsciiBenchmark            -2147483648  avgt   30   6.543 ± 0.018  ns/op
UnsafeBufferPutIntAsciiBenchmark                      0  avgt   30   3.268 ± 0.015  ns/op
UnsafeBufferPutIntAsciiBenchmark                  -9182  avgt   30   7.612 ± 0.040 …
```

[Java] Optimize putIntAscii/putLongAscii methods

---

agrona/src/main/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBuffer.java
agrona/src/main/java/org/agrona/concurrent/ringbuffer/OneToOneRingBuffer.java
agrona/src/main/java/org/agrona/concurrent/ringbuffer/RingBufferDescriptor.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBufferTest.java
agrona/src/test/java/org/agrona/concurrent/ringbuffer/OneToOneRingBufferTest.java

This PR contains the following changes:
- Validate minimum allowed capacity.
- Compute max message length based on the capacity:
* `0` if min capacity.
* `HEADER_LENGTH` if buffer is small.
* `1/8 of the buffer size` - for buffers bigger than `HEADER_LENGTH * 8`.
- `ManyToOneRingBuffer` - handle a case where there is not enough contiguous space in the buffer by inserting padding which once consumed by the consumer allows producer to write again.
- `OneToOneRingBuffer` - handle a case where there is not enough contiguous space in the buffer + directly write a message at the buffer end if it fits and pre-zero start of the buffer.
The latter is only needed to allow writer to proceed immediately once the reader got a previous message, i.e. allows ping pong messages in case of a buffer with …

[Java] RingBuffer capacity validation and fixes.

---

agrona-agent/src/test/java/org/agrona/agent/BufferAlignmentAgentTest.java
agrona-benchmarks/src/main/java/org/agrona/concurrent/UnsafeBufferPutCharSequenceBenchmark.java
agrona/src/main/java/org/agrona/ExpandableArrayBuffer.java
agrona/src/main/java/org/agrona/ExpandableDirectByteBuffer.java
agrona/src/main/java/org/agrona/MutableDirectBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/BufferCharSequenceOperationsTest.java

This PR addresses #238 and contains following changes:
1. Modified `MutableDirectBuffer` class. Added `putStringAscii` and `putStringWithoutLengthAscii` versions that accept `CharSequence` instead of `String`.
1. Implemented them in all subclasses: `UnsafeBuffer`, `ExpandableArrayBuffer`, `ExpandableDirectByteBuffer`.
1. Implementations are copied from String versions verbatim.
1. Added tests in places that contained tests for string versions.
1. Added `BufferCharSequenceOperationsTest` that is based on `BufferStringOperationsTest`.
1. Added simple JMH microbenchmark.
I don't want to seem lazy but these are all changes I was able to come up with to support `CharSequence`-s.

MutableDirectBuffer methods to put string could accept CharSequence

---

agrona/src/main/java/org/agrona/sbe/MessageDecoderFlyweight.java

I've put them with default implementations, so using a newer version of agrona with an older version of SBE won't cause compilation errors.

Additional message decoder flyweight methods.

---

agrona/src/main/java/org/agrona/AsciiEncoding.java
agrona/src/main/java/org/agrona/ExpandableArrayBuffer.java
agrona/src/main/java/org/agrona/ExpandableDirectByteBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/AsciiEncodingTest.java

This PR based on the algorithm by Kendall Willets presented in [Computing the number of digits of an integer even faster](https://lemire.me/blog/2021/06/03/computing-the-number-of-digits-of-an-integer-even-faster/). It replaces existing `endOffset` methods with new `digitCount` methods that are branchless.
Here are the results of running `UnsafeBufferPutLongAsciiBenchmark`:
- Before
```
JDK 8:
Benchmark                                                 (value)  Mode  Cnt   Score   Error  Units
UnsafeBufferPutLongAsciiBenchmark.benchmark  -9223372036854775808  avgt   30   5.728 ± 0.009  ns/op
UnsafeBufferPutLongAsciiBenchmark.benchmark                     0  avgt   30   3.154 ± 0.011  ns/op
UnsafeBufferPutLongAsciiBenchmark.benchmark                 -9182  avgt   30   6.683 ± 0.009  ns/op …
```

[Java] Count digits in a number without using branches.

---

agrona/src/main/java/org/agrona/AsciiEncoding.java
agrona/src/main/java/org/agrona/ExpandableArrayBuffer.java
agrona/src/main/java/org/agrona/ExpandableDirectByteBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/AsciiEncodingTest.java
agrona/src/test/java/org/agrona/MutableDirectBufferTests.java
agrona/src/test/java/org/agrona/concurrent/UnsafeBufferTest.java

This PR makes parsing in chunks of four or eight bytes at a time which improves parsing speed a lot. Here are the latest benchmark results:
```
Benchmark                                                      (value)  Mode  Cnt   Score   Error  Units
MutableDirectBufferParseIntAsciiBenchmark.integerParseInt  -2147483648  avgt   30  16.934 ± 0.020  ns/op
MutableDirectBufferParseIntAsciiBenchmark.integerParseInt  -1234567890  avgt   30  16.932 ± 0.012  ns/op
MutableDirectBufferParseIntAsciiBenchmark.integerParseInt            0  avgt   30   3.828 ± 0.009  ns/op
MutableDirectBufferParseIntAsciiBenchmark.integerParseInt        -9182  avgt   30   8.587 ± 0.013  ns/op
MutableDirectBufferParseIntAsciiBenchmark.integerParseInt     27085146  avgt   30  13.291 ± 0.008  ns/op …
```

[Java] Parse ASCII-encoded numbers in blocks of four/eight bytes at a time.

---

agrona/src/main/java/org/agrona/collections/Int2IntHashMap.java
agrona/src/main/java/org/agrona/collections/Int2ObjectHashMap.java
agrona/src/main/java/org/agrona/collections/IntObjToObjFunction.java
agrona/src/main/java/org/agrona/collections/ObjIntToIntFunction.java
agrona/src/main/java/org/agrona/collections/Object2IntHashMap.java
agrona/src/main/java/org/agrona/collections/Object2ObjectHashMap.java
agrona/src/main/java/org/agrona/generation/SpecialisationGenerator.java
agrona/src/test/java/org/agrona/collections/Int2IntHashMapTest.java
agrona/src/test/java/org/agrona/collections/Int2ObjectHashMapTest.java
agrona/src/test/java/org/agrona/collections/Object2IntHashMapTest.java

As discussed in issue #258, the goal of this PR is to have enhanced compute / computeIfPresent / computeIfAbsent implementations by avoiding doing several lookups in the map as done by the default implementation of j.u.Map
A few remarks : 
- for maps with primitive key/values, the optimized implementations are the one using the primitive API, boxed methods inherited from the j.u.Map API are still using the default implementation
- Behavior of computeIfAbsent for Int2NullableObjectHashMap has been changed to match JDK behavior : if a key is already mapped to null, invoking computeIfAbsent will now compute a new mapping, whereas it just returned null in previous implementation
- Code of put/get methods has not been changed. If we feel there are no performance concern about this, we may …

single lookup implementation of compute methods in maps

---

agrona/src/main/java/org/agrona/concurrent/ShutdownSignalBarrier.java

When the ShutdownSignalBarrier class is loaded, its static initialiser overrides the default JVM Signal handler. This means on shutdown of the JVM, when the SIGTERM signal is sent, the ShutdownSignalBarrier handler class is called. However, as the ShutdownSignalBarrier's registered signal handler does not then call the previous handler (which is what is returned from the Signal.handle(..) method), the JDK does not then run its own shutdown hooks, which can break logic of applications that have other resources they would like to gracefully shut down.
the fix allows the existing registered signal handler to still be called, taking lower priority that the SignalShutdownBarrier.
see issue: https://github.com/real-logic/agrona/issues/270 for full description.

#270 fix shut down signal barrier jvm signal not called

---

agrona/src/main/java/org/agrona/io/DirectBufferDataInput.java
agrona/src/test/java/org/agrona/io/DirectBufferDataInputAgronaTest.java
agrona/src/test/java/org/agrona/io/DirectBufferDataInputJDKTest.java
agrona/src/test/java/org/agrona/io/DirectBufferDataInputTest.java

This PR addresses #273. I have added `DirectBufferDataInput` which implements JDK interface `DataInput`. This implementation adheres to the `DataInput` specification which, sadly, includes throwing checked EOF exception on underflow and being big endian by default. User can change byte order to make it read Agrona buffer's generated data. 
As a bonus it has few additional methods to read Agrona style strings into an `Appendable`.

[Java] DataInput implementation over DirectBuffer

---

agrona/src/main/java/org/agrona/collections/Int2IntHashMap.java
agrona/src/main/java/org/agrona/collections/Object2NullableObjectHashMap.java
agrona/src/main/java/org/agrona/collections/Object2ObjectHashMap.java
agrona/src/test/java/org/agrona/collections/Int2IntHashMapTest.java
agrona/src/test/java/org/agrona/collections/Object2ObjectHashMapTest.java

Currently, only Object2IntHashMap and Int2ObjectHashMap have efficient copy constructors that clone the underlying arrays.
There is no such constructor for Object2ObjectHashMap and Int2IntHashMap.
Since there is no concurrent versions of these map, having such copy constructor is valuable for implementing copy-on-write patterns when the data is mostly read.

add missing copy constructors on Object2ObjectHashMap and Int2IntHashMap

---

agrona/src/main/java/org/agrona/concurrent/SigInt.java

It should fix the following NPE:
```
java.lang.NullPointerException: Cannot throw exception because "t" is null
at org.agrona.LangUtil.rethrow(LangUtil.java:40)
at org.agrona.LangUtil.rethrowUnchecked(LangUtil.java:34)
at org.agrona.concurrent.SigInt.lambda$register$0(SigInt.java:56)
at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
at java.base/jdk.internal.misc.Signal$1.run(Signal.java:219)
at java.base/java.lang.Thread.run(Thread.java:833)
```

Fix NPE in SigInt.java

---

agrona/src/main/java/org/agrona/AbstractMutableDirectBuffer.java
agrona/src/test/java/org/agrona/ExpandableArrayBufferTest.java

Quite minor issue, the `getInt` method should call `boundsCheck0` rather than `ensureCapacity`

[Java] Call bound check instead of capacity expansion in AbstractMutableDirectBuffer.getInt

---

agrona/src/main/java/org/agrona/collections/Int2ObjectCache.java
agrona/src/test/java/org/agrona/collections/Int2ObjectCacheTest.java

Replacing or removing a key might corrupt the cache leading to an exception like this:
```
java.util.NoSuchElementException
at org.agrona.collections.Int2ObjectCache$AbstractIterator.findNext(Int2ObjectCache.java:1180)
at org.agrona.collections.Int2ObjectCache$ValueIterator.next(Int2ObjectCache.java:1215)
```
When shuffling up, we need to clear the last element *after* it has been copied.

[Java] Fix {Int,Long}2ObjectCache.

---

agrona/src/main/java/org/agrona/concurrent/BackoffIdleStrategy.java

Linux by default will not respect the park windows. It will coalesce timer events in 50 us groups. So if you want to wait e.g. 51 us, it could be you need to wait 100 us.
Some documentation was added to explain this and how this can be improved.
For more info see:
https://hazelcast.com/blog/locksupport-parknanos-under-the-hood-and-the-curious-case-of-parking/
https://bugs.openjdk.org/browse/JDK-8307766

Improved documentation for the BackoffIdleStrategy.

---

agrona/src/main/java/org/agrona/collections/ObjectHashSet.java

Whilst profiling our code, ObjectHashSet::addAll was highlighted as method that was allocating due to the lambda function used when calling to disjunction. The same issue applies to removeAll.
By in-lining these calls should resolve the issue.

[TomM] stop allocating on addAll / removeAll on ObjectHashSet.

---

agrona/src/main/java/org/agrona/concurrent/status/AtomicLongPosition.java
agrona/src/main/java/org/agrona/concurrent/status/Position.java
agrona/src/main/java/org/agrona/concurrent/status/ReadablePosition.java
agrona/src/main/java/org/agrona/concurrent/status/UnsafeBufferPosition.java
agrona/src/test/java/org/agrona/concurrent/status/CountersManagerTest.java

For every ordered method, a release method was added. Every ordered method forwards to a release method. So there is a slight performance penalty to pay for the ordered methods.
The ordered methods are from an old naming schema. Since Java 9, the 'release' naming is the used schema.
Also an getAcquire has been added, since release methods typically should be used with an acquire.

Position acquire/release methods

---

agrona/src/main/java/org/agrona/concurrent/status/AtomicCounter.java
agrona/src/test/java/org/agrona/concurrent/status/AtomicCountersTest.java

There was already a getWeak. A more standard naming is 'normal' or 'plain'. So a new method getPlain has been added. Also setPlain and 'incrementPlain' have been added.

AtomicCounter plain methods.

---

agrona/src/main/java/org/agrona/MarkFile.java

This method is a replacement for the timestampOrdered. The ordered methods use an old naming schema and the release methods use the new naming schema.
There is a slight performance penalty because the timestampOrdered calls the timestampRelease method.

MarkFile timestampRelease method

---

agrona/src/main/java/org/agrona/concurrent/AtomicBuffer.java
agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java

Added opaque operations to AtomicBuffer for int/long. An opaque loads/stores provides atomicity and visibility, but it doesn't provide any ordering guarantees beyond coherence. So it doesn't order loads/stores to different addresses (doesn't provide consistency), only to its own address (coherence). Opaque is very much like a C-style volatile and can be used in the same situation as the C++ memory_order_relaxed.
For more info see:
https://gee.cs.oswego.edu/dl/html/j9mm.html
Opaque operations are great for performance counters or progress indicators and provide the least amount of overhead on the CPU (all modern CPUs are coherent); especially ISA's with a weak memory model like ARM or RISC-V. It provides less value on the X86 since every store is a release store and every load is an …

AtomicBuffer opaque methods

---

agrona/src/main/java/org/agrona/concurrent/status/AtomicLongPosition.java

The methods AtomicLongPosition.get and AtomicLongPosition.set, which have plain semantics according to the documentation, are calling AtomicLong.get/set which have volatile semantics. So they are calling methods that are more thread-safe than needed, leading to a potential performance penalty.
The same methods on the UnsafeBufferPosition, do call the right plain methods.

AtomicLongPosition plain methods fix.

---

agrona/src/main/java/org/agrona/concurrent/UnsafeBuffer.java
agrona/src/test/java/org/agrona/concurrent/AtomicBufferTest.java

Add tests to the AtomicBuffer for acq/rel/opaque methods.
Also found and fixed a bug with the opaque int methods. It was checking if there was 'long' space available instead of 'int' space.

Added tests AtomicBuffer acq/rel/opaque methods

---

build.gradle

The error:
Failed to resolve potential dependency for task 'baseline' of project 'agrona' on 'byteBuddy' of project 'agrona' - dependency must be declared manually if appropriate org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':agrona:baseline'.
The cause:
Both 2.3.0-rc1 and 2.3.0-SNAPSHOT match.
Fix:
the release candidates have been excluded from matches. No hard guarantees are given on rc anyway.

Fixes problem with gradle and bytebuddy baseline:
